### ISSUE TITLE
Running in Windows: RuntimeError('Event loop is closed')

### ISSUE THREAD

**Issue by nickpadd** [nickpadd/EuropeanFootballLeaguePredictor#59]
``` bash 
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021E941408B0>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\asyncio\base_events.py", line 515, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
```

**Comment by Manjul1225** [comment]
Hi. 
Please help me.
