### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SoccerCashUK** [nickpadd/EuropeanFootballLeaguePredictor#78]
Using python run_data_collection.py

2024-09-12 17:10:38.783 | SUCCESS  | europeanfootballleaguepredictor.common.config_parser:load_and_extract_yaml_section:38 - Successfully loaded the config.yaml
2024-09-12 17:10:38.788 | SUCCESS  | europeanfootballleaguepredictor.common.config_parser:load_and_extract_yaml_section:47 - Successfully loaded europeanfootballleaguepredictor/data/leagues/EPL/dictionaries/bookmaker.yaml
2024-09-12 17:10:38.790 | SUCCESS  | europeanfootballleaguepredictor.common.config_parser:load_and_extract_yaml_section:47 - Successfully loaded europeanfootballleaguepredictor/data/leagues/EPL/dictionaries/data_co_uk.yaml
2024-09-12 17:10:38.792 | SUCCESS  | europeanfootballleaguepredictor.common.config_parser:load_and_extract_yaml_section:47 - Successfully loaded europeanfootballleaguepredictor/data/leagues/EPL/dictionaries/fixture_download.yaml
2024-09-12 17:10:38.792 | INFO     | __main__:main:42 - Configuration(league='EPL', regressor=<class 'sklearn.linear_model._glm.glm.PoissonRegressor'>, bettor_bank=60, bettor_kelly_cap=0.05, evaluation_output='europeanfootballleaguepredictor/data/leagues/EPL/evaluation/', months_of_form_list=[None, 3], database='europeanfootballleaguepredictor/data/database/EPL_database.db', seasons_to_gather=['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024'], current_season='2024', data_co_uk_path='europeanfootballleaguepredictor/data/leagues/EPL/DataCoUkFiles/', bookmaker_url='https://en.stoiximan.gr/sport/soccer/england/premier-league/1/', bookmaker_dictionary={'Fulham FC': 'Fulham', 'Everton FC': 'Everton', 'Leeds United': 'Leeds', 'Southampton FC': 'Southampton', 'West Ham United': 'West Ham', 'Arsenal FC': 'Arsenal', 'AFC Bournemouth': 'Bournemouth', 'Crystal Palace FC': 'Crystal Palace', 'Liverpool FC': 'Liverpool', 'Brighton & Hove Albion': 'Brighton', 'Chelsea FC': 'Chelsea', 'Tottenham Hotspur': 'Tottenham', 'Brentford FC': 'Brentford', 'Burnley FC': 'Burnley', 'Luton Town': 'Luton', 'Ipswich Town': 'Ipswich'}, data_co_uk_url='https://www.football-data.co.uk/mmz4281/2425/E0.csv', data_co_uk_dictionary={'Man City': 'Manchester City', 'Man United': 'Manchester United', "Nott'm Forest": 'Nottingham Forest', 'Newcastle': 'Newcastle United', 'Wolves': 'Wolverhampton Wanderers', 'West Brom': 'West Bromwich Albion'}, fixture_download_url='https://fixturedownload.com/download/epl-2024-GMTStandardTime.csv', fixture_download_dictionary={'Man City': 'Manchester City', 'Sheffield Utd': 'Sheffield United', 'Man Utd': 'Manchester United', 'Newcastle': 'Newcastle United', 'Spurs': 'Tottenham', 'Wolves': 'Wolverhampton Wanderers', "Nott'm Forest": 'Nottingham Forest'}, voting_dict={'long_term': 0.6, 'short_term': 0.4}, matchdays_to_drop=4)
2024-09-12 17:10:39.304 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2017_2018 created/updated for EPL league.
2024-09-12 17:10:39.689 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2018_2019 created/updated for EPL league.
2024-09-12 17:10:40.157 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2019_2020 created/updated for EPL league.
2024-09-12 17:10:40.632 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2020_2021 created/updated for EPL league.
2024-09-12 17:10:41.055 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2021_2022 created/updated for EPL league.
2024-09-12 17:10:41.595 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2022_2023 created/updated for EPL league.
2024-09-12 17:10:42.029 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2023_2024 created/updated for EPL league.
2024-09-12 17:10:42.501 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2024_2025 created/updated for EPL league.
2024-09-12 17:10:42.503 | INFO     | __main__:main:88 - Gathering None month form data for seasons in ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
2024-09-12 17:10:42.536 | INFO     | europeanfootballleaguepredictor.data.database_handler:get_data:50 - Data fetched for table: DataCoUk_Season2017_2018
2024-09-12 17:10:42.892 | INFO     | europeanfootballleaguepredictor.data.database_handler:save_dataframes:90 - Table DataCoUk_Season2017_2018 created/updated for EPL league.
2024-09-12 17:10:42.894 | INFO     | europeanfootballleaguepredictor.data.understat_gatherer:get_understat_season:62 - Started connection with Understat. Collecting 2017 for EPL and None month(s) of form.
2024-09-12 17:10:42.920 | INFO     | europeanfootballleaguepredictor.data.database_handler:get_data:50 - Data fetched for table: DataCoUk_Season2017_2018
2024-09-12 17:10:43.086 | INFO     | europeanfootballleaguepredictor.data.understat_gatherer:get_understat_season:95 - Collecting Understat data.
  0%|                                                                                          | 0/105 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 105, in <module>
    main()
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 90, in main
    asyncio.run(fetch_data_with_retry(understat_parser, season, months_of_form, table_name))
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 19, in fetch_data_with_retry
    await understat_parser.get_understat_season(season=season, months_of_form=months_of_form, output_table_name=output_table_name)
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\europeanfootballleaguepredictor\data\understat_gatherer.py", line 105, in get_understat_season
    table = await understat.get_league_table(self.league, season , end_date = str(unique_dates[i]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Understat.get_league_table() got an unexpected keyword argument 'end_date'

C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master>

**Comment by SoccerCashUK** [comment]
Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 105, in <module>
    main()
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 90, in main
    asyncio.run(fetch_data_with_retry(understat_parser, season, months_of_form, table_name))
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\run_data_collection.py", line 19, in fetch_data_with_retry
    await understat_parser.get_understat_season(season=season, months_of_form=months_of_form, output_table_name=output_table_name)
  File "C:\Users\Iphon\Downloads\EuropeanFootballLeaguePredictor-master\EuropeanFootballLeaguePredictor-master\europeanfootballleaguepredictor\data\understat_gatherer.py", line 105, in get_understat_season
    table = await understat.get_league_table(self.league, season , end_date = str(unique_dates[i]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Understat.get_league_table() got an unexpected keyword argument 'end_date'

**Comment by nickpadd** [comment]
Can you please provide me with the installed dependancies of your environment?

If you are using poetry:
```
poetry show --tree
```

If you are using pip:
```
pip freeze
```
